Extension { #name : 'UITheme' }

{ #category : '*DrTests' }
UITheme >> diffHighlightCoveredNodes [

	"Answer the color used to show the border of the changes."

	^ colorPalette diffHighlightCoveredNodes
]

{ #category : '*DrTests' }
UITheme >> diffHighlightUncoveredNodes [

	"Answer the color used to show the border of the changes."

	^ colorPalette diffHighlightUncoveredNodes
]

{ #category : '*DrTests' }
UITheme >> diffHighlightYellowNodes [

	"Answer the color used to show the border of the changes."

	^ colorPalette diffHighlightYellowNodes
]
